<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Curso extends \Application\Entity\Curso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'titulo', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'palavrasChave', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'dataLimite', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'categoriaCurso', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'instrutor'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'titulo', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'palavrasChave', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'dataLimite', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'categoriaCurso', '' . "\0" . 'Application\\Entity\\Curso' . "\0" . 'instrutor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Curso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPalavrasChave($palavrasChave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPalavrasChave', [$palavrasChave]);

        return parent::setPalavrasChave($palavrasChave);
    }

    /**
     * {@inheritDoc}
     */
    public function getPalavrasChave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPalavrasChave', []);

        return parent::getPalavrasChave();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataLimite($dataLimite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataLimite', [$dataLimite]);

        return parent::setDataLimite($dataLimite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataLimite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataLimite', []);

        return parent::getDataLimite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoriaCurso(\Application\Entity\CategoriaCurso $categoriaCurso = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoriaCurso', [$categoriaCurso]);

        return parent::setCategoriaCurso($categoriaCurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoriaCurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoriaCurso', []);

        return parent::getCategoriaCurso();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstrutor(\Application\Entity\Instrutor $instrutor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstrutor', [$instrutor]);

        return parent::setInstrutor($instrutor);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstrutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstrutor', []);

        return parent::getInstrutor();
    }

}
