
                    <a class="hover-btn edit" href="#" ng-click="edit()" title="Editar"> <span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="hover-btn add" href="#" data-toggle="modal" data-target=".modal-confirmDelete" title="Remover"> <span class="glyphicon glyphicon-trash"></span></a>
                    <?php include(__DIR__.'/../../modals/confirmDelete.phtml') ?>