<a class="btn btn-sm btn-primary pull-right"
   href="<?php echo $this->url('curso'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
</a>
<h3><?php echo utf8_encode($form->getLabel()); ?></h3>
<?php echo $this->form()->openTag($form);?>
<div class="form-group">
    <label for="inputTitulo">Título</label>
    <?php echo $this->formInput($form->get('titulo'));?>
</div>
<div class="form-group">
    <label for="inputPalavrasChave">Palavras Chave</label>
    <?php echo $this->formTextArea($form->get('palavrasChave'));?>
</div>
<div class="form-group">
    <label for="inputDataLimite">Data Limite</label>
    <?php echo $this->formDate($form->get('dataLimite'));?>
</div>
<div class="form-group">
    <label for="inputCategoria">Categoria</label>
    <?php echo $this->formSelect($form->get('categoriaCurso'));?>
</div>
<div class="form-group">
    <label for="inputInstrutor">Instrutor</label>
    <?php echo $this->formSelect($form->get('instrutor'));?>
</div>
<div class="form-group">
    <div class="panel-group" id="accordionVideo" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingOne">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordionVideo" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                        Vídeos
                    </a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                <div class="panel-body" ng-init='videos = <?php echo json_encode($form->getAttribute('videos')); ?>'>
                    <table id="indexTable" class="table table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>Url</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody ng-repeat="row in videos | filter:filtro">
                            <tr class="registro accordion-toggle" id=video{{row.id}} ng-controller="videosCursoController" ng-click="selectRow()" data-toggle="collapse" data-target="#videos{{row.id}}">
                                <td>{{row.nome}}</td>
                                <td>{{row.url}}</td>
                                <td>
                                    <?php include(__DIR__.'/../../layout/indexRowButtons.phtml') ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="panel-group" id="accordionAtividade" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingThree">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordionAtividade" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Atividades
                    </a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                <div class="panel-body" ng-init='atividades = <?php echo json_encode($form->getAttribute('atividades')); ?>'>
                    <table id="indexTable" class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Descrição</th>
                            <th>Tipo</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody ng-repeat="row in atividades | filter:filtro">
                        <tr class="registro accordion-toggle" id=atividade{{row.id}} ng-controller="atividadesCursoController" ng-click="selectRow()" data-toggle="collapse" data-target="#atividades{{row.id}}">
                            <td>{{row.nome}}</td>
                            <td>{{row.descricao}}</td>
                            <td>{{row.tipoAtividade.nome}}</td>
                            <td>
                                <?php include(__DIR__.'/../../layout/indexRowButtons.phtml') ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="panel-group" id="accordionMaterial" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="headingTwo">
                <h4 class="panel-title">
                    <a role="button" data-toggle="collapse" data-parent="#accordionMaterial" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Material
                    </a>
                </h4>
            </div>
            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body" ng-init='materiais = <?php echo json_encode($form->getAttribute('materiais')); ?>'>
                    <table id="indexTable" class="table table-hover table-condensed">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Arquivo</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody ng-repeat="row in materiais | filter:filtro">
                        <tr class="registro accordion-toggle" id=material{{row.id}} ng-controller="materiaisCursoController" ng-click="selectRow()" data-toggle="collapse" data-target="#materiais{{row.id}}">
                            <td>{{row.nome}}</td>
                            <td>{{row.arquivo}}</td>
                            <td>
                                <?php include(__DIR__.'/../../layout/indexRowButtons.phtml') ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
</div>
<?php echo $this->form()->closeTag($form);?>