<div ng-controller="indexController" ng-init='data = <?php echo json_encode($data); ?>'>

    <h3><?php echo utf8_encode($title); ?></h3>

    <form class="navbar-form navbar-right" role="search">
        <!-- Filtros e Ordenação -->
        <div class="form-group has-feedback">
            <input type="search" class="form-control input-sm" aria-describedby="Pesquisar" placeholder="Pesquisar..." ng-model="filtro.$">
        </div>
        <!-- Novo -->
        <div class="form-group has-feedback">
            <a class="btn btn-sm btn-primary pull-right" ng-click="add()" href="#">
                <span class="glyphicon glyphicon-plus"></span> Adicionar
            </a>
        </div>
    </form>

    <table class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>Título</th>
                <th>Palavras Chave</th>
                <th>Data Limite</th>
                <th>Categoria</th>
                <th>Instrutor</th>
                <th>Editar</th>
                <th>Remover</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="row in data | filter:filtro" ng-controller="indexRowController">
                <td>
                    {{row.titulo}}
                </td>
                <td>
                    {{row.palavrasChave}}
                </td>
                <td>
                    {{row.dataLimite}}
                </td>
                <td>
                    {{row.categoriaCurso.nome}}
                </td>
                <td>
                    {{row.instrutor.nome}}
                </td>
                <td>
                    <a class="edit" href="#" ng-click="edit()" title="Editar"> <span class="glyphicon glyphicon-edit"></span> Editar</a>
                </td>
                <td>
                    <a class="add" href="#" data-toggle="modal" data-target=".modal-confirmDelete"> <span class="glyphicon glyphicon-trash"></span> Remover</a>
                    <?php include(__DIR__.'/../../modals/confirmDelete.phtml') ?>
                </td>
            </tr>
        </tbody>
    </table>

</div>