<?php

namespace Application\Repository;

/**
 * CategoriaCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
