<?php

namespace Application\Repository;

/**
 * InscricaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscricaoRepository extends \Doctrine\ORM\EntityRepository
{
}
