<?php

namespace Application\Repository;

/**
 * InstrutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrutorRepository extends \Doctrine\ORM\EntityRepository
{
}
