<?php

namespace Application\Repository;

/**
 * StatusAtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusAtividadeRepository extends \Doctrine\ORM\EntityRepository
{
}
