<?php

namespace Application\Repository;

/**
 * StatusMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
