<?php

namespace Application\Repository;

/**
 * StatusVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
