<?php

namespace Application\Repository;

/**
 * StatusQuestaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusQuestaoRepository extends \Doctrine\ORM\EntityRepository
{
}
