<?php

namespace Application\Repository;

/**
 * UnidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
