<?php

namespace Application\Repository;
use Application\Entity\Usuario;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByEmailAndSenha(Usuario $usuario, $email, $senha)
    {
        /** @var Usuario $userLogin */
        $userLogin = $this->createQueryBuilder('u')
            ->where('u.email = :a1')
            ->setParameter('a1', $email)->getQuery()->getOneOrNullResult();

        if(!is_null($userLogin)){
            $usuario->setSalt($userLogin->getSalt());

            if($usuario->encryptSenha($senha) == $userLogin->getSenha()){
                return $userLogin;
            }
        }
    }
}
