<a class="btn btn-sm btn-primary pull-right"
   href="<?php echo $this->url('questao'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
</a>
<h3><?php echo $form->getLabel(); ?></h3>
<?php echo $this->form()->openTag($form);?>
<div class="form-group">
    <label for="inputDescricao">Descrição</label>
    <?php echo $this->formRow($form->get('descricao'));?>
</div>
<div class="form-group">
    <label for="inputTipo">Atividade</label>
    <?php echo $this->formSelect($form->get('atividade'));?>
</div>
<div class="form-group">
    <input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
</div>
<?php echo $this->form()->closeTag($form);?>