<div ng-controller="indexController" ng-init='data = <?php echo json_encode($data); ?>'>

    <?php include(__DIR__.'/../../layout/indexTitle.phtml') ?>

    <?php include(__DIR__.'/../../layout/indexNavbar.phtml') ?>

    <table id="indexTable" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>Descrição</th>
                <th>Atividade</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="registro" id={{row.id}} ng-repeat="row in data | filter:filtro" ng-controller="indexRowController" ng-click="selectRow()">
                <td>{{row.descricao}}</td>
                <td>{{row.atividade.nome}}</td>
                <td>
                    <?php include(__DIR__.'/../../layout/indexRowButtons.phtml') ?>
                </td>
            </tr>
        </tbody>
    </table>

</div>