<a class="btn btn-sm btn-primary pull-right"
   href="<?php echo $this->url('material'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
</a>
<h3><?php echo utf8_encode($form->getLabel()); ?></h3>
<?php include(__DIR__.'/../../layout/formErrors.phtml') ?>
<div class="form-group">
    <label for="inputNome">Nome</label>
    <?php echo $this->formRow($form->get('nome'));?>
</div>
<div class="form-group">
    <label for="inputArquivo">Arquivo</label>
    <?php echo $this->formFile($form->get('arquivo'));?>
</div>
<div class="form-group">
    <label for="inputCurso">Curso</label>
    <?php echo $this->formSelect($form->get('curso'));?>
</div>
<div class="form-group">
    <label for="inputCurso">Unidade</label>
    <?php echo $this->formSelect($form->get('unidade'));?>
</div>
<div class="form-group">
    <label for="inputCurso">Ordem</label>
    <?php echo $this->formRow($form->get('nrordem'));?>
</div>
<div class="form-group">
    <input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
</div>
<?php echo $this->form()->closeTag($form);?>