<a class="btn btn-sm btn-primary pull-right"
   href="<?php echo $this->url('atividade'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
</a>
<h3><?php echo utf8_encode($form->getLabel()); ?></h3>
<?php echo $this->form()->openTag($form);?>
<?php
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
    ->setMessageCloseString('</div>')
    ->render($form);
?>
<div class="form-group">
    <label for="inputNome">Nome</label>
    <?php echo $this->formRow($form->get('nome'));?>
</div>
<div class="form-group">
    <label for="inputDescricao">Descricao</label>
    <?php echo $this->formRow($form->get('descricao'));?>
</div>
<div class="form-group">
    <label for="inputCurso">Curso</label>
    <?php echo $this->formSelect($form->get('curso'));?>
</div>
<div class="form-group">
    <label for="inputTipo">Tipo</label>
    <?php echo $this->formSelect($form->get('tipoAtividade'));?>
</div>
<div class="form-group">
    <label for="inputUnidade">Unidade</label>
    <?php echo $this->formSelect($form->get('unidade'));?>
</div>
<div class="form-group">
    <label for="inputOrdem">Ordem</label>
    <?php echo $this->formNumber($form->get('nrordem'));?>
</div>
<div class="form-group">
    <input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
</div>
<?php echo $this->form()->closeTag($form);?>