<div ng-controller="indexController" ng-init='data = <?php echo json_encode($data); ?>'>

    <?php include(__DIR__.'/../../layout/indexTitle.phtml') ?>

    <?php include(__DIR__.'/../../layout/indexNavbar.phtml') ?>

    <table id="indexTable" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Tipo</th>
                <th>Curso</th>
                <th>Unidade</th>
                <th>Ordem</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr class="registro" id={{row.id}} ng-repeat="row in data | filter:filtro" ng-controller="indexRowController" ng-click="selectRow()">
                <td>{{row.nome}}</td>
                <td>{{row.descricao}}</td>
                <td>{{row.curso.titulo}}</td>
                <td>{{row.tipoAtividade.nome}}</td>
                <td>{{row.unidade.descricao}}</td>
                <td>{{row.nrordem}}</td>
                <td>
                    <?php include(__DIR__.'/../../layout/indexRowButtons.phtml') ?>
                </td>
            </tr>
        </tbody>
    </table>

</div>