<?php
echo $this->flashMessenger()
    ->setMessageOpenFormat('<div%s>')
    ->setMessageSeparatorString('</p><p>')
    ->setMessageCloseString('<button type="button" class="close" data-dismiss="alert">x</button>')
    ->render('success',array('alert alert-success'));
?>
<?php echo $this->form()->openTag($form);?>
<?php
echo $this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
    ->setMessageCloseString('</div>')
    ->render($form);
?>