<form class="navbar-form navbar-right" role="search">
    <div class="form-group has-feedback">
        <a class="btn btn-sm btn-primary" ng-click="add()" href="#">
            <span class="glyphicon glyphicon-plus"></span> Novo
        </a>
    </div>
    <!-- Filtros e Ordenação -->
    <div class="form-group has-feedback">
        <input type="search" class="form-control input-sm" aria-describedby="Pesquisar" placeholder="Pesquisar..." ng-model="filtro.$">
    </div>
</form>