<a class="btn btn-sm btn-primary pull-right"
   href="<?php echo $this->url('resposta'); ?>">
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
</a>
<h3><?php echo utf8_encode($form->getLabel()); ?></h3>
<?php echo $this->form()->openTag($form);?>
<div class="form-group col-sm-12">
    <label for="inputDescricao">Descrição</label>
    <?php echo $this->formRow($form->get('descricao'));?>
</div>
<div class="form-group col-sm-6">
    <label for="inputIdcorreta">Correta</label>
    <?php echo $this->formSelect($form->get('idcorreta'));?>
</div>
<div class="form-group col-sm-6">
    <label for="inputTipo">Questão</label>
    <input type="hidden" name="questao" value="<?php echo $form->getAttribute('fk1'); ?>">
    <?php
    echo $form->getAttribute('action');
    if ($form->getAttribute('fk1')) {
        $form->get('questao')->setAttribute('disabled', 'disabled');
    }
    echo $this->formSelect($form->get('questao'));
    ?>
</div>
<div class="form-group col-sm-12">
    <input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
</div>
<?php echo $this->form()->closeTag($form);?>