<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center"><?php echo $form->getLabel(); ?></h3>
            </div>

            <div class="panel-body" ng-controller="avaliacaoController">
                <?php include(__DIR__.'/../../../../Application/view/layout/formErrors.phtml') ?>
                <?php echo $this->form()->openTag($form);?>
                <div class="form-group">
                    <label><?php echo $form->getAttribute('inscricao')->getCurso()->getTitulo(); ?></label>
                </div>
                <div class="form-group">
                    <label for="inputComentario">Comentário</label>
                    <?php echo $this->formTextArea($form->get('comentario'));?>
                </div>
                <div class="form-group">
                    <label for="inputNota">Nota</label>
                    <?php echo $this->formNumber($form->get('nota'));?>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
                </div>
                <?php echo $this->form()->closeTag($form);?>
            </div>
        </div>
    </div>
</div>