<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center"><?php echo $this->translate('Certificados') ?></h3>
            </div>

            <div class="panel-body">
                <div ng-init='inscricoes = <?php echo json_encode($inscricoes); ?>'>
                    <ul ng-repeat="inscricao in inscricoes | filter:filtro | orderBy:'inscricao.nota'">
                        <a ng-controller="certificadosController" ng-click="certificado()">
                            <li>{{inscricao.curso.titulo}} - Nota: {{inscricao.nota}}
                        </a>
                    </ul>
                </div>
            </div>

            <img src="/tcc/public/img/colosseum-img.png" alt="Arena Training"/>
        </div>
    </div>
</div>
