<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default" ng-init='usuario = <?php echo json_encode($usuario); ?>'>
            <div class="panel-heading">
                <h3 class="panel-title text-center"><?php echo $this->translate('Inscrições') ?></h3>
            </div>

            <div class="panel-body">
                <div ng-init='cursos = <?php echo json_encode($cursos); ?>; inscricoes = <?php echo json_encode($inscricoes); ?>'>
                    <ul ng-repeat="curso in cursos">
                        <a ng-controller="inscricoesCursoController" ng-click="vercurso(curso.id)">
                            <li ng-show="inscrito(curso.id)">
                                {{curso.titulo}} - até {{curso.dataLimite}} - Instrutor: {{curso.instrutor.nome}} - Inscrito
                            </li>
                            <li ng-show="naoinscrito(curso.id)">
                                {{curso.titulo}} - até {{curso.dataLimite}} - Instrutor: {{curso.instrutor.nome}} - Inscrever-se
                            </li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
