<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default" ng-init='inscricao = <?php echo json_encode($inscricao); ?>'>

            <div class="panel-heading">
                <h3 class="panel-title text-center">{{inscricao.curso.titulo}}</h3>
            </div>

            <div class="panel-body">
                <div>
                    <h3>Detalhes</h3>
                    <p>Data Limite: {{inscricao.curso.dataLimite}}</p>
                    <p>Instrutor: {{inscricao.curso.instrutor.nome}}</p>
                    <div ng-init='unidades= <?php echo json_encode($unidades); ?>'>
                        <div ng-repeat="unidade in unidades | filter:filtro" ng-controller="meuCursoUnidadeController">
                            <h3>{{unidade.descricao}}</h3>
                            <ul>
                                <div ng-init='videos= <?php echo json_encode($videos); ?>'>
                                    <h4>Vídeos</h4>
                                    <ul ng-repeat="video in videos | filter:filtroUnidade">
                                        <li>
                                            <a class="alert-link" ng-controller="meuCursoAtividadeController" ng-click="meuvideo()">
                                                {{video.nrordem}} - {{video.nome}}
                                            </a>
                                            <br/>
                                            <iframe src="{{video.url}}" width="WIDTH" height="HEIGHT" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                                        </li>
                                    </ul>
                                </div>
                                <div ng-init='atividades = <?php echo json_encode($atividades); ?>'>
                                    <h4>Atividades</h4>
                                    <ul ng-repeat="atividade in atividades | filter:filtroUnidade">
                                        <li>
                                            <a class="alert-link" ng-controller="meuCursoAtividadeController" ng-click="minhaatividade()">
                                                {{atividade.nome}} - {{atividade.tipoAtividade.nome}}
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <h4>Materiais</h4>
                                <div ng-init='materiais = <?php echo json_encode($materiais); ?>'>
                                    <ul ng-repeat="material in materiais | filter:filtroUnidade">
                                        <li>
                                            <a class="alert-link" ng-controller="meuCursoAtividadeController" ng-click="meumaterial()">
                                                {{material.nome}}
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
