<div class="container-fluid">
    <div class="panel panel-default" ng-init='material = <?php echo json_encode($material); ?>'>

        <div class="panel-heading">
            <h3 class="panel-title text-center">{{material.nome}}</h3>
        </div>

        <div class="panel-body">
            <video width="320" height="240" controls>
                <source src="<?php echo $material['arquivo']; ?>" type="video/mp4; codecs='mp4v.20.240, mp4a.40.2'">
                <source src="<?php echo $material['arquivo']; ?>" type="video/ogg">
                Your browser does not support the video tag.
            </video>
        </div>

    </div>
</div>