<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center"><?php echo $this->translate('Meus Cursos') ?></h3>
            </div>

            <div class="panel-body">
                <div ng-init='inscricoes = <?php echo json_encode($inscricoes); ?>'>
                    <ul ng-repeat="inscricao in inscricoes | filter:filtro | orderBy:'curso.dataLimite'">
                        <a ng-controller="meusCursosController" ng-click="meucurso()">
                            <li>{{inscricao.curso.titulo}} - até {{inscricao.curso.dataLimite}} - Nota: {{inscricao.nota}}</li>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
